VacationModule/Models/VacationRequest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Christoc.Modules.VacationModule.Models
{
    public class VacationRequest
    {

        public string IDEmployee { get; set; }
        public string NameEmployee { get; set; }

        public string TelefonoOfi { get; set; }
        public string Extension { get; set; }
        public string TelefonoMov { get; set; }
        public bool AniversarioCumplido { get; set; }
        public bool AniversarioNoCumplido { get; set; }
        public int CantidadDias { get; set; }
        public List<string> DiasTomar { get; set; }
        public string NombreJefeDirecto { get; set; }
        public string EmailJefeDirecto { get; set; }
        public string NombreSupervisor { get; set; }
        public string EmailSupervisor { get; set; }

        public int ModuleID { get; set; }
        public string EmailUser { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public object Attachment { get; set; }
        public int StatusID { get; set; }
        public int AgentID { get; set; }
        public int ChannelID { get; set; }


        public VacationRequest()
        {
            this.IDEmployee = string.Empty;
            this.NameEmployee = string.Empty;

            this.TelefonoOfi = string.Empty;
            this.Extension = string.Empty;
            this.TelefonoMov = string.Empty;
            this.AniversarioCumplido = false;
            this.AniversarioNoCumplido = false;
            this.CantidadDias = 0;
            this.DiasTomar = new List<string>();
            this.NombreJefeDirecto = string.Empty;
            this.EmailJefeDirecto = string.Empty;
            this.NombreSupervisor = string.Empty;
            this.EmailSupervisor = string.Empty;

            this.EmailUser = string.Empty;
            this.Subject = string.Empty;
            this.Message = string.Empty;

        }

    }
}

VacationModule/Controllers/VacationController.cs
using Christoc.Modules.VacationModule.Models;
using DotNetNuke.Web.Mvc.Framework.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Christoc.Modules.VacationModule.Controllers
{
    public class VacationController : DnnController
    {
        // GET: Vacation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VacationRequest()
        {
            return View();
        }

        public FileResult DownloadRequest()
        {
            var report = MainModel.GetInstance().FileBase64;
            byte[] file = Convert.FromBase64String(report);
            return File(file, "application/pdf", "Solicitud-" + DateTime.Now.ToShortDateString() + " " + DateTime.Now.ToShortTimeString() + ".pdf");
        }
    }
}

VacationModule/Views/Vacation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />


<div class="row">
    <div class="col-md-12">
        <br /><br />
        @Html.ActionLink("Solicitar Vacaciones", "VacationRequest", "Vacation", new { }, new { @class = "btn btn-success", @style = "color:#FFF" })
    </div>
</div>

<div class="row">
    <br /><br />
    <div class="col-md-12">
        <table id="tb_vacation">
            <thead>
                <tr>
                    <th>No. de Empleado</th>
                    <th>Nombre Completo</th>
                    <th>Antigüedad</th>
                    <th>Días pendientes de disfrute</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="~/desktopmodules/mvc/VacationModule/Scripts/main.js"></script>

VacationModule/Views/Vacation/VacationRequest.cshtml
@{
    ViewBag.Title = "VacationRequest";
}



<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/desktopmodules/mvc/VacationModule/Styles/main.css" rel="stylesheet" />
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
<link href="~/desktopmodules/mvc/VacationModule/Styles/datepicker.css" rel="stylesheet" />

<div class="row">
    <br /><br />
    <div class="col-md-12">
        <p>Por favor llenar la siguiente información para la elaboraciópn del documento de solicitud de vacaciones.</p>
    </div>
    <div class="col-md-12">
        <div class="form-group col-md-4">
            <label>Telefono de Oficina: </label>
            <input type="text" class="form-control phone_with_ddd" id="txt_telefonoOficina" />
        </div>
        <div class="form-group col-md-4">
            <label>Extensión: </label>
            <input type="text" class="form-control extension" id="txt_extension" />
        </div>
        <div class="form-group col-md-4">
            <label>Telefono Móvil: </label>
            <input type="text" class="form-control phone" id="txt_telefonoMovil" />
        </div>
    </div>
    <div class="col-md-12">
        <label>Vacaciones correspondientes a aniversario cumplido: </label>
        <input type="checkbox" checked data-toggle="toggle" id="chk_aniversarioCumplido">
    </div>
    <div class="col-md-12">
        <label>Permiso a cuenta de Vacaciones correspondientes a mi siguiente aniversario x cumplir: </label>
        <input type="checkbox" checked data-toggle="toggle" id="chk_aniversarioNoCumplido">
    </div>

    <div class="col-md-6">
        <br /><br />
        <br />
        <div class="col-md-12">
            <label>Cantidad de Días Solicitados a Disfrutar: </label>
            <input type="number" class="form-control" id="txt_cantidadDiasSolicitados" value="0" />
        </div>
        <div class="col-md-12">
            <label>Días a tomar: </label>
            <input type="text" class="form-control datepicker" id="txt_fechasATomar" />
            <button type="button" class="btn btn-info" id="btn_agregarFecha">Agregar</button>
        </div>
        <div class="col-md-12">
            <label>Nombre de Jefe Directo: </label>
            <input type="text" class="form-control" id="txt_nombreJefeDirecto" onkeypress="return validarLetras(event)" />
        </div>
        <div class="col-md-12">
            <label>Email de Jefe Directo: </label>
            <input type="text" class="form-control" id="txt_emailJefeDirecto" onkeyup="validarEmailInput(this.id,'txt_message_EmailJefeDirecto','emailJefeDirectoOk');" data-emailJefeDirectoOk="0" />
            <span class="" id="txt_message_EmailJefeDirecto"></span>
        </div>
        <div class="col-md-12">
            <label>Nombre de Supervisor Directo de TASISOFT: </label>
            <input type="text" class="form-control" id="txt_nombreSupervisor" onkeypress="return validarLetras(event)" />
        </div>
        <div class="col-md-12">
            <label>Email de Supervisor Directo de TASISOFT: </label>
            <input type="text" class="form-control" id="txt_emailSupervisor" onkeyup="validarEmailInput(this.id,'txt_message_EmailSupervisor','emailSupervisorOk');" data-emailSupervisorOk="0" />
            <span class="" id="txt_message_EmailSupervisor"></span>
        </div>
    </div>


    <div class="col-md-6">
        <br /><br />
        <button type="button" onclick="RemoveRow(); return false;" class="btn btn-danger">Remover dia</button>
        <br /><br />
        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Días a tomar</th>
                </tr>
            </thead>
        </table>
        <br />
        <span class="text-primary bg-info" style="font-weight:bold;">Para remover alguna fecha elegida, seleccione la fila y de clic en Remover Día</span>
    </div>
</div>

<div class="row">
    <br /><br />
    <div class="col-md-12">
        <div class="alert" role="alert">

        </div>
    </div>
</div>
<div class="row">
    <br /><br />
    <div class="col-md-12">
        <div class="col-md-6">
            <button type="button" class="btn btn-success" id="btn_generarSolicitud">Generar Solicitud</button>
        </div>
    </div>
</div>


<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="~/desktopmodules/mvc/VacationModule/Scripts/main.js"></script>
<script src="~/desktopmodules/mvc/VacationModule/Scripts/jquery.mask.js"></script>
<script src="~/desktopmodules/mvc/VacationModule/Scripts/datepicker.js"></script>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>